name: SET_CACHE

on:
  workflow_dispatch:

jobs:
  #Job 1
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Use Cache
      - name: step-1 Use Cache
        id: use-cache
      - uses: actions/cache@v4
        env:
          cache-name: go-cache
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ runner.os }}-build-${{ runner.os }}-
