name: USE_FILTERS_TO_REFINE_TRIGGERS

on:
  push:
    branches:
      - 'main'
      - 'main/**'
      - '!main/**-fix'
    tags:
      - '*PROD'
    paths:
      - '**.c'
      - '!*/docs/**'
     
jobs:
  notify-for-filters:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered passing all filters ..."
