name: C Simple Cache

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Restore build cache
        uses: actions/cache@v4
        with:
          path: build
          key: c-build-${{ runner.os }}-${{ hashFiles('**/*.c') }}
          restore-keys: |
            c-build-${{ runner.os }}-

      - name: Build C program
        env: 
          USER_ID: ${{ vars.FILE_TO_CHECK }}
        run: |
          echo "::group::Extended info ..."
          echo "::add-mask::$USER_ID"
          echo "USER_ID is $USER_ID"
          echo "FILENAME: ${{ vars.FILE_TO_CHECK }}
          echo "::add-mask::
          echo "::debug::This is a debug message"
          echo "::warning::This is a warning message"
          echo "::notice::This is a notice message"
          echo "::endgroup::"
          mkdir -p build
          gcc hello-world.c -o build/hello-world

      - name: Run program
        run: |
          ./build/hello-world
          #echo "::error file=hello-world.yml,line=32,col=5,endColumn=8::This is an error message:
          echo "Job-1 Completed" >> $GITHUB_STEP_SUMMARY
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Unit Test - 1
        run: |
          echo "Running unit test - 1"

      - name: Unit test - 2
        run: |
          echo "Running unit test - 2"
          echo "Testing Summary Follows:" >> $GITHUB_STEP_SUMMARY
          echo " | Test | Result | " >> $GITHUB_STEP_SUMMARY
          echo " | ----:| ------:| " >> $GITHUB_STEP_SUMMARY
          echo " | 1 | :white_check_mark: | " >> $GITHUB_STEP_SUMMARY
          echo " | 2 | :no_entry_sign: | " >> $GITHUB_STEP_SUMMARY
      
