name: SECRET Security Vulnerability

on:
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Safe usage of SECRET
        env:
          DATA_VALUE: ${{ secrets.SECURITY_TEST }}
        run: |
            echo $DATA_VALUE
