name: Security Vulnerability

on:
  push:
    branches: [ "main" ]

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
    # Security Vulnerability with the below command
    # - run: echo ${{ github.event.head_commit.message }}

    # Security Vulnerability with the below command - Fixed
      - env:
          DATA_VALUE: ${{ github.event.head_commit.message }}
      - run: echo $DATA_VALUE
