# This is a first self-hosted workflow
name: SELF_HOSTED_RUNNER_WF

on:
   workflow_dispatch:

jobs:
  self-hosted-demo:
    runs-on: self-hosted
    steps:
    - name: Run Echo Statements
      run: |
          echo XYZ
          echo ABC
