# This is a first self-hosted workflow
name: SELF_HOSTED_RUNNER_WF_UPDATED
run-name: SELF_HOSTED_RUNNER_WF_UPDATED by ${{ github.actor }}

on:
   workflow_dispatch:
# Env setting at WF level
env:
   PIPE: cicd
jobs:
  report-url:
     runs-on: self-hosted
     steps:
        - run: echo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
        - run: echo $env:GITHUB_SERVER_URL/$env:GITHUB_REPOSITORY/actions/runs/$env:GITHUB_RUN_ID
        - run: echo ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  self-hosted-demo:
     runs-on: self-hosted
     env:
        STAGE: dev
     steps:
       - name: Run Echo Statements
       # Env setting at STEP level
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
            echo XYZ
            echo ABC
            #echo $PIPE
            #echo $GITHUB_TOKEN

      
      
         
         
