# This is a first self-hosted workflow
name: SELF_HOSTED_RUNNER_WF
run-name: SELF_HOSTED_RUNNER_WF by ${{ github.actor }}

on:
   workflow_dispatch:
# Env setting at WF level
env:
   PIPE: cicd
jobs:
  self-hosted-demo:
     runs-on: self-hosted
     steps:
       - name: Run Echo Statements
       # Env setting at STEP level
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
            echo XYZ
            echo ABC
            echo $PIPE
            echo $GITHUB_TOKEN
